### ISSUE TITLE
Q2 2019 OKR - Bootstrap the IPFS package manager community

### ISSUE THREAD

**Issue by achingbrain** [ipfs/package-managers#29]
Create a place package manager maintainers can hang out in to talk about and get help with using IPFS.

**Comment by jessicaschilling** [comment]
Would it be reasonable to investigate whether there are existing channels (either ours or others') where we can reach the package manager maintainer community, rather than build a new channel and address the additional challenge of attracting traffic to it?

**Comment by andrew** [comment]
Have you seen https://package.community, it’s a community chat room on discord but not easily searchable or organised into threads

**Comment by jessicaschilling** [comment]
Nice! Exactly that kind of stuff. HN, Reddit, etc etc?

**Comment by andrew** [comment]
There's also a package management subreddit that I started last year, pretty quiet though: https://www.reddit.com/r/packagemanagement/

**Comment by jessicaschilling** [comment]
Added a row for "existing communications channels" to the top-level package manager audience analysis Mural here (it's at the bottom):
https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1557168696127/577c9453a3c51199c8163cf0fe5701294e55f99b
This doc doesn't include specific forum URLs -- rather it's a categorization of types of comms channels that I'd like to blow out later into lists of specific channels. That said, would love it if folks could take a look and see if either new channel categories or specific channels come to mind!

**Comment by andrew** [comment]
@jessicaschilling good list, one change might be to list "source repos" rather than "github repos" so as not to exclude [gitlab](https://gitlab.com/), [bitbucket](https://bitbucket.org), [sourcehut](https://sourcehut.org) that are also used for similar purposes as GitHub and can be channels of communication.

**Comment by andrew** [comment]
@jessicaschilling another channel is "mailing list" which both package managers and individual packages have, could be grouped in with forums but didn't want it to get left out.

**Comment by jessicaschilling** [comment]
@andrew - Thanks for catching my github-specific blinders 😄 As for mailing lists vs forums ... good call. Functionally speaking they should probably be separate for purposes of this diagram simply because even if mailing lists might be intended to be used as means for two-way conversation, in practice they tend to be much more of a broadcast medium than forums/discussion boards. Changed the board accordingly. Thanks!
